version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000

    volumes:
      - /app/node_modules # create bookmark
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev # we use Dockerfile of development but overwrite CMD part
    volumes:
      - /app/node_modules # create bookmark
      - .:/app
    command: ["npm", "run", "test"]